AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create a secret in AWS Secrets Manager for BTG challenge

Resources:
  BtgChallengeSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'btg-challenge-secrets1'
      Description: 'Secret for BTG challenge containing CORS origin and AWS mail topic ARN'
      SecretString: !Sub |
        {
          "CORS_ORIGIN": "${CorsOrigin}",
          "AWS_MAIL_TOPIC_ARN": "${AwsMailTopicArn}"
        }
      Tags:
        - Key: 'Purpose'
          Value: 'BTG Challenge Secrets'

Parameters:
  CorsOrigin:
    Type: String
    Description: 'The URL for CORS origin'
    Default: ''

  AwsMailTopicArn:
    Type: String
    Description: 'The ARN for AWS mail topic'
    Default: ''

Outputs:
  BtgChallengeSecretARN:
    Description: 'ARN of the BTG challenge secret'
    Value: !Ref BtgChallengeSecret
